server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
      - labels:
          stream:
      - static_labels:
          app: teddy-open-finance
          environment: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    relabel_configs:
      - source_labels: [__path__]
        regex: /var/lib/docker/containers/([^/]+)/.*-json\.log
        target_label: container_id
      - source_labels: [__path__]
        regex: .*
        replacement: ''
        target_label: filename
