global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: teddy-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend-1:3000
          - backend-2:3000
        labels:
          app: teddy-open-finance
          environment: production
